### ISSUE TITLE
Bug: brave doesnt open

### ISSUE THREAD

**Issue by bn0785ac** [netblue30/firejail#1797]
commit: r3568.f6502ebf

https://p.teknik.io/9sHff

**Comment by bn0785ac** [comment]
https://github.com/netblue30/firejail/commit/f6502ebf237a54a9914c80f386f321772f0e8063

**Comment by netblue30** [comment]
We had a problem with Brave about one year ago - #1110 
What version of firejail and brave are you using?

**Comment by bn0785ac** [comment]
this  (git version)
https://github.com/netblue30/firejail/commit/f6502ebf237a54a9914c80f386f321772f0e8063

**Comment by bn0785ac** [comment]
pd with this  profile (#1110)  

all worked

**Comment by Fred-Barclay** [comment]
I've just done some poking around and it looks like the line `noexec /tmp` in /etc/firejail/chromium-config.profile causes this.
Sample output below:
```
user1@Mint183-VM ~/.config/firejail $ firejail brave
Reading profile /home/user1/.config/firejail/brave.profile
Reading profile /home/user1/.config/firejail/chromium-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 5048, child pid 5049
Child process initialized in 52.92 ms
[40:40:0305/103556.369482:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib/brave/swiftshader/libGLESv2.so: /usr/lib/brave/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[40:40:0305/103556.373516:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[49:49:0305/103556.448630:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib/brave/swiftshader/libGLESv2.so: /usr/lib/brave/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[49:49:0305/103556.452885:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[57:57:0305/103556.539878:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib/brave/swiftshader/libGLESv2.so: /usr/lib/brave/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[57:57:0305/103556.544079:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[65:65:0305/103556.623775:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib/brave/swiftshader/libGLESv2.so: /usr/lib/brave/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[65:65:0305/103556.638349:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[6:30:0305/103556.642420:ERROR:browser_gpu_channel_host_factory.cc(121)] Failed to launch GPU process.
Crash reporting enabled
An uncaught exception occurred in the main process Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.49MRfr: failed to map segment from shared object
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/usr/lib/brave/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at bindings (/usr/lib/brave/resources/app.asar/node_modules/leveldown/node_modules/bindings/bindings.js:76:44)
    at /usr/lib/brave/resources/app.asar/node_modules/leveldown/leveldown.js:4:46

Crash dump id: 14e0211817b74343
Waiting 60 seconds for process to load
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'getIn' of null
    at registerComponents (/usr/lib/brave/resources/app.asar/app/extensions.js:593:28)
    at Object.module.exports.init (/usr/lib/brave/resources/app.asar/app/extensions.js:598:3)
    at perWindowStateLoaded (/usr/lib/brave/resources/app.asar/app/index.js:198:16)
    at Immediate.setImmediate (/usr/lib/brave/resources/app.asar/app/index.js:188:24)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate (timers.js:617:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Crash dump id: 9e1f1bdc76ce1a0d
Waiting 60 seconds for process to load
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'get' of null
    at Object.getExtensions (/usr/lib/brave/resources/app.asar/app/common/state/extensionState.js:17:18)
    at ComponentUpdater.componentUpdater.on (/usr/lib/brave/resources/app.asar/app/extensions.js:385:39)
    at emitTwo (events.js:106:13)
    at ComponentUpdater.emit (events.js:194:7)

Crash dump id: 0cf50aa00bc5701b
Waiting 60 seconds for process to load
An uncaught exception occurred in the main process Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.49MRfr: failed to map segment from shared object
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/usr/lib/brave/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at bindings (/usr/lib/brave/resources/app.asar/node_modules/leveldown/node_modules/bindings/bindings.js:76:44)
    at /usr/lib/brave/resources/app.asar/node_modules/leveldown/leveldown.js:4:46

Crash dump id: 3b12d5145798c286
Waiting 60 seconds for process to load
```

**Comment by bn0785ac** [comment]
thanks

worked here (4.16)
