### ISSUE TITLE
Torbrowser won't launch in Firejail: OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Zypherspace** [netblue30/firejail#2449]
Torbrowser won't launch in Firejail: OSError: [Errno 13] Permission denied

```
$ firejail torbrowser-launcher %u
Reading profile /usr/local/etc/firejail/torbrowser-launcher.profile
Reading profile /usr/local/etc/firejail/globals.local
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-interpreters.inc
Reading profile /usr/local/etc/firejail/disable-passwdmgr.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Reading profile /usr/local/etc/firejail/disable-xdg.inc
Reading profile /usr/local/etc/firejail/whitelist-common.inc
Reading profile /usr/local/etc/firejail/whitelist-var-common.inc
Parent pid 18989, child pid 18990

Interface        MAC                IP               Mask             Status
lo                                  127.0.0.1        255.0.0.0        UP    
eth0-18989       9a:39:72:01:72:66  192.168.50.145   255.255.255.0    UP    
Default gateway 192.168.50.1

Warning: skipping ca-certificates for private /etc
Warning fcopy: skipping /etc/crypto-policies/back-ends/openssh-server.config, cannot find inode
Private /etc installed in 51.88 ms
56 programs installed in 72.04 ms
Post-exec seccomp protector enabled
Seccomp list in: @clock,@cpu-emulation,@debug,@module,@obsolete,@raw-io,@reboot,@resources,@swap,acct,add_key,bpf,fanotify_init,io_cancel,io_destroy,io_getevents,io_setup,io_submit,ioprio_set,kcmp,keyctl,mount,name_to_handle_at,nfsservctl,ni_syscall,open_by_handle_at,personality,pivot_root,process_vm_readv,ptrace,remap_file_pages,request_key,setdomainname,sethostname,syslog,umount,umount2,userfaultfd,vhangup,vmsplice, check list: @default-keep, prelist: adjtimex,clock_adjtime,clock_settime,settimeofday,modify_ldt,lookup_dcookie,perf_event_open,process_vm_writev,delete_module,finit_module,init_module,_sysctl,afs_syscall,create_module,get_kernel_syms,getpmsg,putpmsg,query_module,security,sysfs,tuxcall,uselib,ustat,vserver,ioperm,iopl,kexec_load,kexec_file_load,reboot,set_mempolicy,migrate_pages,move_pages,mbind,swapon,swapoff,acct,add_key,bpf,fanotify_init,io_cancel,io_destroy,io_getevents,io_setup,io_submit,ioprio_set,kcmp,keyctl,mount,name_to_handle_at,nfsservctl,open_by_handle_at,personality,pivot_root,process_vm_readv,ptrace,remap_file_pages,request_key,setdomainname,sethostname,syslog,umount2,userfaultfd,vhangup,vmsplice,
Child process initialized in 1201.99 ms
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.1
https://github.com/micahflee/torbrowser-launcher

(python2:79): dbind-WARNING **: 19:46:51.156: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-W6WR0xbCwM: Connection refused
Qt: Session management error: Could not open network socket
Launching Tor Browser.
('Running', '/home/user/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop')
Traceback (most recent call last):
  File "/usr/local/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/__init__.py", line 81, in main
    gui = Launcher(common, app, url_list)
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 152, in __init__
    self.update()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 199, in update
    self.start(None)
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 218, in start
    self.run_task()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 266, in run_task
    self.run()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 436, in run
    subprocess.call([self.common.paths['tbb']['start']], cwd=self.common.paths['tbb']['dir_tbb'])
  File "/usr/lib64/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by rusty-snake** [comment]
@Zypherspace works it with `--noprofile`? (`firejail --noprofile torbrowser-launcher`)

For what is the `%u`?

**Comment by Zypherspace** [comment]
Found solution:

```shell
torbrowser-launcher --settings
```
