### ISSUE TITLE
The nuclear.profile doesn't work with --no-sandbox

### ISSUE THREAD

**Issue by mYnDstrEAm** [netblue30/firejail#4422]
#3883 and #3806 could be related

When running `firejail --profile=/etc/firejail/nuclear.profile nuclear` I get `The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/nuclear/chrome-sandbox is owned by root and has mode 4755.`

When appending `--no-sandbox` to the command it shows these errors:
```
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965
      main › Sqlite database creation failed
      main › DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at new t (/opt/nuclear/resources/app.asar/dist/main.js:2680:723535)
    at t.loadDependencies (/opt/nuclear/resources/app.asar/dist/main.js:2680:592613)
    at new t (/opt/nuclear/resources/app.asar/dist/main.js:2680:591154)
    at e.create (/opt/nuclear/resources/app.asar/dist/main.js:2680:70627)
    at new e (/opt/nuclear/resources/app.asar/dist/main.js:2680:23774)
    at e.create (/opt/nuclear/resources/app.asar/dist/main.js:2680:32984)
    at /opt/nuclear/resources/app.asar/dist/main.js:2682:12651
    at /opt/nuclear/resources/app.asar/dist/main.js:2699:2716
    at Object.next (/opt/nuclear/resources/app.asar/dist/main.js:2699:2821)
    at /opt/nuclear/resources/app.asar/dist/main.js:2699:1758
    at new Promise (<anonymous>)
    at Module.u (/opt/nuclear/resources/app.asar/dist/main.js:2699:1503)
    at t.createConnection (/opt/nuclear/resources/app.asar/dist/main.js:2682:12385)
    at bn.connect (/opt/nuclear/resources/app.asar/dist/main.js:2711:488198)
    at App.<anonymous> (/opt/nuclear/resources/app.asar/dist/main.js:2711:529294)
    at App.emit (events.js:327:22)
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
   ipc api › error in event get-localfolders => Cannot read property 'find' of undefined
   ipc api › TypeError: Cannot read property 'find' of undefined
    at bn.getLocalFolders (/opt/nuclear/resources/app.asar/dist/main.js:2711:488573)
    at Qn.getLocalFolders (/opt/nuclear/resources/app.asar/dist/main.js:2711:496490)
    at IpcMainImpl.<anonymous> (/opt/nuclear/resources/app.asar/dist/main.js:2711:528433)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10351)
    at Object.emit (events.js:315:20)
```

Is there another way one is supposed to solve this electron problem or is the nuclear.profile broken?

**Bug and expected behavior**
It should run the Nuclear music player or display an error message that tells the user exactly what to do / run to make it work.

**No profile and disabling firejail**

**Reproduce**
1. Run the commands above on Debian10

**Environment**
Debian10 stable
Firejail version 0.9.64.4

**Additional context**

**Checklist**
 - [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [x] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [x] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [x] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
 - [x] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.

**Comment by rusty-snake** [comment]
Did you set `force-nonewprivs yes`? 
Do you have a globals.local or nuclear.local or electron.local?

**Comment by mYnDstrEAm** [comment]
No, I didn't.
No, I didn't have a nuclear.local.
I get this:
```
(node:3) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EACCES: permission denied, open '/home/username/.config/nuclear/config.json'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.readFileSync (fs.js:377:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8643)
    at e.exports.get store [as store] (/opt/nuclear/resources/app.asar/dist/main.js:2118:1196475)
    at new y (/opt/nuclear/resources/app.asar/dist/main.js:2118:1192456)
    at new e.exports (/opt/nuclear/resources/app.asar/dist/main.js:2165:49188)
    at Module../src/main.ts (/opt/nuclear/resources/app.asar/dist/main.js:2711:461516)
    at r (/opt/nuclear/resources/app.asar/dist/main.js:1:118)
    at /opt/nuclear/resources/app.asar/dist/main.js:1:1544

(nuclear:3): Gtk-WARNING **: 12:07:28.990: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(nuclear:3): Gtk-WARNING **: 12:07:28.990: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(nuclear:3): Gtk-WARNING **: 12:07:28.990: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
```

**Comment by rusty-snake** [comment]
The "The SUID sandbox helper binary was found, but is not configured correctly." Issue should be gone since f4f6767458208a127084e4c0103fab88761d9056. What does `firejail --profile=nuclear cat /proc/self/status | grep NoNewPrivs` show? (It should be and must be `NoNewPrivs:	1`).

Does it work with `--noprofile`? Does `--ignore=apparmor` help?

> Error: EACCES: permission denied, open '/home/username/.config/nuclear/config.json'

nuclear.profile has `noblacklist ${HOME}/.config/nuclear`. From where does this come (check `--debug`)?

**Comment by mYnDstrEAm** [comment]
`NoNewPrivs:     1`
Should I set that in nuclear.local?
`--debug` doesn't have more info as far as I could see and shows just the same error messag at the end (it also has things like `Installing /run/firejail/mnt/seccomp/seccomp.protocol seccomp filter` before).

**Comment by rusty-snake** [comment]
Why does it install a seccomp filter? It should not do this. It must not do this.

**Comment by rusty-snake** [comment]
There is no `protocol` in
- https://github.com/netblue30/firejail/blob/0.9.64.4/etc/profile-m-z/nuclear.profile
- https://github.com/netblue30/firejail/blob/0.9.64.4/etc/profile-a-l/electron.profile

From where does it come?

**Comment by mYnDstrEAm** [comment]
The two profiles match those in the repo and there is no electron.local or nuclear.local. How to find out from where it comes?

**Comment by mYnDstrEAm** [comment]
`firejail --ignore=apparmor --ignore=no3d --profile=/etc/firejail/nuclear.profile nuclear --no-sandbox` doesn't work either. Are those error messages of any use in finding the cause of this? Why does the SQLite package fail?

**Comment by rusty-snake** [comment]
Because it talks about js files and npm you maybe need to allow this stuff (`ignore include disable-interpreters.inc` and `ignore include disable-programs.inc` for now). Anyway I'm still thinking why NNP is set/from where the protocol seccomp filters come. Can you post the `--debug` output.

**Comment by mYnDstrEAm** [comment]
Output of the above command:
```
...
Mounting tmpfs on /run/firejail/mnt directory
Creating empty /run/firejail/mnt/seccomp directory
Creating empty /run/firejail/mnt/seccomp/seccomp.protocol file
Creating empty /run/firejail/mnt/seccomp/seccomp.postexec file
Creating empty /run/firejail/mnt/seccomp/seccomp.postexec32 file
Mounting /proc filesystem representing the PID namespace
...
Mounting noexec /run/firejail/mnt/pulse
1788 1286 0:78 /pulse /run/firejail/mnt/pulse rw,nosuid,nodev,noexec - tmpfs tmpfs rw,mode=755
mountid=1788 fsname=/pulse dir=/run/firejail/mnt/pulse fstype=tmpfs
Creating empty /home/username/.config/pulse directory
Drop privileges: pid 22, uid 1000, gid 1000, nogroups 0
Mounting /run/firejail/mnt/pulse on /home/username/.config/pulse
1789 1370 0:78 /pulse /home/username/.config/pulse rw,nosuid,nodev,noexec - tmpfs tmpfs rw,mode=755
mountid=1789 fsname=/pulse dir=/home/username/.config/pulse fstype=tmpfs
Current directory: /home/username
DISPLAY=:0 parsed as 0
Mounting read-only /run/firejail/mnt/seccomp
1791 1286 0:78 /seccomp /run/firejail/mnt/seccomp ro,nosuid - tmpfs tmpfs rw,mode=755
mountid=1791 fsname=/seccomp dir=/run/firejail/mnt/seccomp fstype=tmpfs
Seccomp directory:
ls /run/firejail/mnt/seccomp
drwxr-xr-x root     root             120 .
drwxr-xr-x root     root             440 ..
-rw-r--r-- 1000     1000            1072 seccomp
-rw-r--r-- 1000     1000             808 seccomp.32
-rw-r--r-- 1000     1000               0 seccomp.postexec
-rw-r--r-- 1000     1000               0 seccomp.postexec32
No active seccomp files
Dropping all capabilities
Drop privileges: pid 1, uid 1000, gid 1000, nogroups 1
No supplementary groups
Starting application
....
```

**Comment by rusty-snake** [comment]
> Dropping all capabilities

It must not do this.

**Comment by rusty-snake** [comment]
> Found nuclear.local profile in /home/username/.config/firejail directory

This is empty as I got you 

> Found whitelist-var-common.inc profile in /home/username/.config/firejail directory

and this must only contain `whitelist /var/foobarbaz` commands.

**Comment by mYnDstrEAm** [comment]
Yes, it's empty...I even moved out #commented out lines.
I don't think I created a whitelist-var-common.inc file so it must have been created by default and I didn't change it. It only includes whitelists of /var/ directories and include whitelist-var-common.local

**Comment by rusty-snake** [comment]
> so it must have been created by default

Neither firejail nor your package manager write to $HOME/.config/firejail resp. $HOME. Anyway "It only includes whitelists of /var/ directories".

**Comment by mYnDstrEAm** [comment]
I'm sure that I haven't created that file or only created it because it was part of some guide to get something to work with the file's contents to be pasted in but forgot about it. This is the file's contents, I don't think it's why it doesn't run:
```
# Local customizations come here
include whitelist-var-common.local

# common /var whitelist for all profiles

whitelist /var/lib/dbus
whitelist /var/lib/menu-xdg
whitelist /var/cache/fontconfig
whitelist /var/tmp
whitelist /var/run
whitelist /var/lock
```
/home/username/.config/firejail/whitelist-var-common.local doesn't exist. Any ideas how to get Nuclear to work? Also attaching `--disable-setuid-sandbox` isn't needed right?

**Comment by rusty-snake** [comment]
What does the disable-common.local contain?

**Comment by mYnDstrEAm** [comment]
Only `blacklist ${HOME}/...` entries
None of those directories is used by Nuclear. I didn't even block blacklist ${HOME}/Music for example. (caps.drop all and apparmor are #commented out).

**Comment by rusty-snake** [comment]
> caps.drop all and apparmor are #commented out

In disable-common.local? Since when?

**Comment by mYnDstrEAm** [comment]
I think since before I tried these things. It was just a note that's most likely irrelevant as these are commented out anyway but it's what I'd try to (re)include if everything works fine otherwise.

**Comment by rusty-snake** [comment]
So it was already commented when you got "[Dropping all capabilities](https://github.com/netblue30/firejail/issues/4422#issuecomment-886814788)".

Btw does it work without firejail or with --noprofile?

**Comment by mYnDstrEAm** [comment]
I commented it out [at this point](https://github.com/netblue30/firejail/issues/4428#issuecomment-889051217). The output of `` is slightly different:
```
[...]
Disable /usr/local/lib/python3.7
Disable /usr/local/lib/python3.6
Not blacklist /home/username/.config/nuclear
Mounting read-only /tmp/.X11-unix
1763 1696 254:1 /tmp/.X11-unix /tmp/.X11-unix ro,nosuid,nodev,noexec,relatime master:1 - ext4 /dev/mapper/name rw,errors=remount-ro
mountid=1763 fsname=/tmp/.X11-unix dir=/tmp/.X11-unix fstype=ext4
Disable /sys/fs
Disable /sys/module
Disable /mnt
Disable /media
Disable /run/mount
Mounting noexec /run/firejail/mnt/pulse
1769 1270 0:77 /pulse /run/firejail/mnt/pulse rw,nosuid,nodev,noexec - tmpfs tmpfs rw,mode=755
mountid=1769 fsname=/pulse dir=/run/firejail/mnt/pulse fstype=tmpfs
Creating empty /home/username/.config/pulse directory
Drop privileges: pid 22, uid 1000, gid 1000, nogroups 0
Mounting /run/firejail/mnt/pulse on /home/username/.config/pulse
1770 1351 0:77 /pulse /home/username/.config/pulse rw,nosuid,nodev,noexec - tmpfs tmpfs rw,mode=755
mountid=1770 fsname=/pulse dir=/home/username/.config/pulse fstype=tmpfs
Current directory: /home/username/
DISPLAY=:0 parsed as 0
Mounting read-only /run/firejail/mnt/seccomp
1772 1270 0:77 /seccomp /run/firejail/mnt/seccomp ro,nosuid - tmpfs tmpfs rw,mode=755
mountid=1772 fsname=/seccomp dir=/run/firejail/mnt/seccomp fstype=tmpfs
Seccomp directory:
ls /run/firejail/mnt/seccomp
drwxr-xr-x root     root             120 .
drwxr-xr-x root     root             440 ..
-rw-r--r-- 1000     1000            1072 seccomp
-rw-r--r-- 1000     1000             808 seccomp.32
-rw-r--r-- 1000     1000               0 seccomp.postexec
-rw-r--r-- 1000     1000               0 seccomp.postexec32
No active seccomp files
Set caps filter 240000
Drop privileges: pid 1, uid 1000, gid 1000, nogroups 1
No supplementary groups
Starting application
LD_PRELOAD=(null)
execvp argument 0: nuclear
execvp argument 1: --no-sandbox
Child process initialized in 897.22 ms
Searching $PATH for nuclear
trying #/home/username/local/Python36/bin/nuclear#
trying #/home/username/.nvm/versions/node/v12.22.2/bin/nuclear#
trying #/usr/local/bin/nuclear#
trying #/usr/bin/nuclear#
monitoring pid 23

      main › (node:23) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)

(nuclear:23): Gtk-WARNING **: ...: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(nuclear:23): Gtk-WARNING **: ...: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(nuclear:23): Gtk-WARNING **: ...: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
      main › Sqlite database creation failed
      main › DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
[...]
```

**Comment by mYnDstrEAm** [comment]
Now it does start but it still shows these errors (and takes a bit too long to launch).  
Furthermore the nuclear.local profile file in /home/username/.config/firejail directory wasn't just commented out lines anymore but had the following contents I didn't write`(they are different from the contents [here](https://github.com/netblue30/firejail/issues/4422#issuecomment-891969201)):
```
################################
# Generic GUI application profile
################################
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-programs.inc
include /etc/firejail/disable-passwdmgr.inc

#blacklist ${HOME}/.wine

caps.drop all
netfilter
nonewprivs
noroot
protocol unix,inet,inet6
seccomp
```
So I think this file was generated / overwritten somehow (however its metadata has modified & created in June 2020).

Maybe it's working now because of the upgrade from Debian 10 to 11. Looks like the issue can be closed.

The output of `firejail nuclear` now is:
```
Reading profile /etc/firejail/nuclear.profile
Reading profile /etc/firejail/disable-shell.inc
Reading profile /etc/firejail/electron.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-common.local
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /home/username/.config/firejail/whitelist-var-common.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid ...., child pid ....
Private /opt installed in xx9.9x ms
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning fcopy: skipping /etc/alternatives/js, cannot find inode
Warning fcopy: skipping /etc/alternatives/js.1.gz, cannot find inode
Warning: skipping asound.conf for private /etc
Warning: skipping crypto-policies for private /etc
Warning: skipping pki for private /etc
Warning fcopy: skipping /etc/pulse/client.conf.d/01-enable-autospawn.conf, cannot find inode
Private /etc installed in xx.86 ms
Warning: skipping alsa for private /usr/etc
Warning: skipping alternatives for private /usr/etc
Warning: skipping asound.conf for private /usr/etc
Warning: skipping ca-certificates for private /usr/etc
Warning: skipping crypto-policies for private /usr/etc
Warning: skipping fonts for private /usr/etc
Warning: skipping gtk-2.0 for private /usr/etc
Warning: skipping gtk-3.0 for private /usr/etc
Warning: skipping host.conf for private /usr/etc
Warning: skipping hostname for private /usr/etc
Warning: skipping hosts for private /usr/etc
Warning: skipping mime.types for private /usr/etc
Warning: skipping nsswitch.conf for private /usr/etc
Warning: skipping pki for private /usr/etc
Warning: skipping pulse for private /usr/etc
Warning: skipping resolv.conf for private /usr/etc
Warning: skipping selinux for private /usr/etc
Warning: skipping ssl for private /usr/etc
Warning: skipping X11 for private /usr/etc
Warning: skipping xdg for private /usr/etc
Private /usr/etc installed in 0.x5 ms
Child process initialized in xx3.90 ms
      main › (node:23) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open /dev/dri/card0: No such file or directory
libGL error: failed to load driver: iris
      main › Sqlite database creation failed
      main › DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at new t (/opt/nuclear/resources/app.asar/dist/main.js:2680:723535)
    at t.loadDependencies (/opt/nuclear/resources/app.asar/dist/main.js:2680:592613)
    at new t (/opt/nuclear/resources/app.asar/dist/main.js:2680:591154)
    at e.create (/opt/nuclear/resources/app.asar/dist/main.js:2680:70627)
    at new e (/opt/nuclear/resources/app.asar/dist/main.js:2680:23774)
    at e.create (/opt/nuclear/resources/app.asar/dist/main.js:2680:32984)
    at /opt/nuclear/resources/app.asar/dist/main.js:2682:12651
    at /opt/nuclear/resources/app.asar/dist/main.js:2699:2716
    at Object.next (/opt/nuclear/resources/app.asar/dist/main.js:2699:2821)
    at /opt/nuclear/resources/app.asar/dist/main.js:2699:1758
    at new Promise (<anonymous>)
    at Module.u (/opt/nuclear/resources/app.asar/dist/main.js:2699:1503)
    at t.createConnection (/opt/nuclear/resources/app.asar/dist/main.js:2682:12385)
    at bn.connect (/opt/nuclear/resources/app.asar/dist/main.js:2711:488198)
    at App.<anonymous> (/opt/nuclear/resources/app.asar/dist/main.js:2711:529294)
    at App.emit (events.js:327:22)
   ipc api › error in event get-localfolders => Cannot read property 'find' of undefined
   ipc api › TypeError: Cannot read property 'find' of undefined
    at bn.getLocalFolders (/opt/nuclear/resources/app.asar/dist/main.js:2711:488573)
    at Qn.getLocalFolders (/opt/nuclear/resources/app.asar/dist/main.js:2711:496490)
    at IpcMainImpl.<anonymous> (/opt/nuclear/resources/app.asar/dist/main.js:2711:528433)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10351)
    at Object.emit (events.js:315:20)
   ipc api › error in event get-metas => Cannot read property 'find' of undefined
   ipc api › TypeError: Cannot read property 'find' of undefined
    at bn.getTracks (/opt/nuclear/resources/app.asar/dist/main.js:2711:488952)
    at Qn.getLocalMetas (/opt/nuclear/resources/app.asar/dist/main.js:2711:496403)
    at IpcMainImpl.<anonymous> (/opt/nuclear/resources/app.asar/dist/main.js:2711:528433)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10351)
    at Object.emit (events.js:315:20)
(node:89) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `exe --trace-deprecation ...` to show where the warning was created)
```
(After `at Object.emit (events.js:315:20)` it's taking too long to load, and I don't know what those errors are about.)
