### ISSUE TITLE
telegram xpra fail

### ISSUE THREAD

**Issue by nntb2a** [netblue30/firejail#797]
Hello
firejail --noprofile --x11=xpra telegram-desktop

*** Attaching to xpra display 669 ***
             
2016-09-19 18:40:18,047 unknown logging category: x265
2016-09-19 18:40:18,084 xpra client version 0.14.27
libGL error: failed to open drm device: Permission denied
libGL error: failed to load driver: i965
2016-09-19 18:40:18,548 PyOpenGL warning: missing accelerate module
2016-09-19 18:40:18,548 PyOpenGL warning: missing array format handlers: numeric, vbo, vbooffset
2016-09-19 18:40:18,548 OpenGL Version: 3.0 Mesa 11.0.6
2016-09-19 18:40:18,550 OpenGL support could not be enabled:
2016-09-19 18:40:18,550  vendor 'VMware, Inc.' is blacklisted!
2016-09-19 18:40:18,580 Importing BmpImagePlugin
2016-09-19 18:40:18,582 Importing BufrStubImagePlugin
2016-09-19 18:40:18,583 Importing CurImagePlugin
2016-09-19 18:40:18,583 Importing DcxImagePlugin
2016-09-19 18:40:18,583 Importing EpsImagePlugin
2016-09-19 18:40:18,585 Importing FitsStubImagePlugin
2016-09-19 18:40:18,585 Importing FliImagePlugin
2016-09-19 18:40:18,585 Importing FpxImagePlugin
2016-09-19 18:40:18,587 Importing GbrImagePlugin
2016-09-19 18:40:18,587 Importing GifImagePlugin
2016-09-19 18:40:18,588 Importing GribStubImagePlugin
2016-09-19 18:40:18,588 Importing Hdf5StubImagePlugin
2016-09-19 18:40:18,589 Importing IcnsImagePlugin
2016-09-19 18:40:18,591 Importing IcoImagePlugin
2016-09-19 18:40:18,591 Importing ImImagePlugin
2016-09-19 18:40:18,592 Importing ImtImagePlugin
2016-09-19 18:40:18,593 Importing IptcImagePlugin
2016-09-19 18:40:18,593 Importing JpegImagePlugin
2016-09-19 18:40:18,609 Importing Jpeg2KImagePlugin
2016-09-19 18:40:18,610 Importing McIdasImagePlugin
2016-09-19 18:40:18,610 Importing MicImagePlugin
2016-09-19 18:40:18,610 Importing MpegImagePlugin
2016-09-19 18:40:18,611 Importing MpoImagePlugin
2016-09-19 18:40:18,611 Importing MspImagePlugin
2016-09-19 18:40:18,611 Importing PalmImagePlugin
2016-09-19 18:40:18,613 Importing PcdImagePlugin
2016-09-19 18:40:18,613 Importing PcxImagePlugin
2016-09-19 18:40:18,613 Importing PdfImagePlugin
2016-09-19 18:40:18,613 Importing PixarImagePlugin
2016-09-19 18:40:18,614 Importing PngImagePlugin
2016-09-19 18:40:18,614 Importing PpmImagePlugin
2016-09-19 18:40:18,614 Importing PsdImagePlugin
2016-09-19 18:40:18,615 Importing SgiImagePlugin
2016-09-19 18:40:18,615 Importing SpiderImagePlugin
2016-09-19 18:40:18,615 Importing SunImagePlugin
2016-09-19 18:40:18,616 Importing TgaImagePlugin
2016-09-19 18:40:18,616 Importing TiffImagePlugin
2016-09-19 18:40:18,616 Importing WebPImagePlugin
2016-09-19 18:40:18,618 Importing WmfImagePlugin
2016-09-19 18:40:18,618 Importing XbmImagePlugin
2016-09-19 18:40:18,623 Importing XpmImagePlugin
2016-09-19 18:40:18,623 Importing XVThumbImagePlugin
2016-09-19 18:40:18,628 keyboard layouts: us,ru
2016-09-19 18:40:18,658 dbus setup error: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory   
2016-09-19 18:40:18,680 detected keyboard: rules=evdev, model=pc104, layout=us,ru
2016-09-19 18:40:18,682 desktop size is 1280x800 with 1 screen(s):
2016-09-19 18:40:18,682   ':1.0' (338x211 mm)
2016-09-19 18:40:18,683     LVDS1 (261x163 mm)
2016-09-19 18:40:18,684 sound support not available: No module named sound
Xpra server pid 23842, client pid 23877
root@evo ~ # 2016-09-19 18:40:18,855 mmap is enabled using 128MB area in /tmp/xpra.xDebDm.mmap
2016-09-19 18:40:18,856 server: Linux Funtoo Linux - baselayout  2.2.1 , Xpra version 0.14.27 (r9763)
2016-09-19 18:40:18,858 Attached to :669 (press Control-C to detach)
             
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/xpra/client/gtk2/client.py", line 417, in _process_raise_window
    if window.has_toplevel_focus():
AttributeError: 'ClientTray' object has no attribute 'has_toplevel_focus'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/xpra/client/ui_client_base.py", line 800, in _process_pointer_grab
    self.window_grab(window)
  File "/usr/lib64/python2.7/site-packages/xpra/client/gtk2/client.py", line 425, in window_grab
    gtk.gdk.pointer_grab(window.gdk_window(), owner_events=True, event_mask=mask)
AttributeError: 'ClientTray' object has no attribute 'gdk_window'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/xpra/client/ui_client_base.py", line 800, in _process_pointer_grab
    self.window_grab(window)
  File "/usr/lib64/python2.7/site-packages/xpra/client/gtk2/client.py", line 425, in window_grab
    gtk.gdk.pointer_grab(window.gdk_window(), owner_events=True, event_mask=mask)
AttributeError: 'ClientTray' object has no attribute 'gdk_window'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/xpra/client/ui_client_base.py", line 800, in _process_pointer_grab
    self.window_grab(window)
  File "/usr/lib64/python2.7/site-packages/xpra/client/gtk2/client.py", line 425, in window_grab
    gtk.gdk.pointer_grab(window.gdk_window(), owner_events=True, event_mask=mask)
AttributeError: 'ClientTray' object has no attribute 'gdk_window'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/xpra/client/ui_client_base.py", line 800, in _process_pointer_grab
    self.window_grab(window)
  File "/usr/lib64/python2.7/site-packages/xpra/client/gtk2/client.py", line 425, in window_grab
    gtk.gdk.pointer_grab(window.gdk_window(), owner_events=True, event_mask=mask)
AttributeError: 'ClientTray' object has no attribute 'gdk_window'

the python errors throws up, when i click on the tray icon (which is the only one working) and trying to get some windows. no xpra tweaking helps.

xpra log:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/xpra/x11/gtk_x11/window.py", line 927, in do_xpra_property_notify_event
    BaseWindowModel.do_xpra_property_notify_event(self, event)
  File "/usr/lib64/python2.7/site-packages/xpra/x11/gtk_x11/window.py", line 413, in do_xpra_property_notify_event
    self._handle_property_change(str(event.atom))
  File "/usr/lib64/python2.7/site-packages/xpra/x11/gtk_x11/window.py", line 421, in _handle_property_change
    self._call_property_handler(name)
  File "/usr/lib64/python2.7/site-packages/xpra/x11/gtk_x11/window.py", line 425, in _call_property_handler
    self._property_handlers[name](self)
  File "/usr/lib64/python2.7/site-packages/xpra/x11/gtk_x11/window.py", line 1237, in _handle_motif_wm_hints
    if motif_hints and motif_hints.flags&(2**MotifWMHints.DECORATIONS_BIT):
NameError: global name 'MotifWMHints' is not defined

**Comment by nntb2a** [comment]
it is gentoo/funtoo system, firejail      Installed versions:  0.9.40-r2(12:03:25 AM 09/07/2016)(bind chroot file-transfer network seccomp userns x11 -network-restricted)  xpra      Installed versions:  0.14.27(12:01:42 AM 09/07/2016)(client clipboard csc opengl rencode server vpx webp x264 x265 -dec_av -dec_av2 -libav -pulseaudio -sound PYTHON_TARGETS="python2_7")

**Comment by nntb2a** [comment]
sorry, it is really xpra fault. updating xpra seems to fix the problem

**Comment by netblue30** [comment]
No problem. We are getting lots of xpra bugs lately, I think they are going through a transition to pytohon 3 and breaking python 2.7 all over the place.
