### ISSUE TITLE
Open Folder/File not working in Deluge under KDE4

### ISSUE THREAD

**Issue by fld** [netblue30/firejail#906]
**Debian 8.6, kde-desktop**

Trying to open a torrent folder or file inside firejailed deluge:
```
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/lib/python2.7/dist-packages/deluge/ui/client.py", line 179, in dataReceived
    d.callback(request[2])
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/deluge/ui/gtkui/files_tab.py", line 365, in _on_open_file
    deluge.common.open_file(filepath, timestamp=timestamp)
  File "/usr/lib/python2.7/dist-packages/deluge/common.py", line 254, in open_file
    subprocess.Popen(["xdg-open", "%s" % path], env=env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
exceptions.OSError: [Errno 2] No such file or directory
```
Ok, so we need to add xdg-open to the private-bin list:
```
/usr/local/bin/xdg-open: 472: /usr/local/bin/xdg-open: kfmclient: not found
```
Ok, so we need to add kfmclient to the private-bin list...
```
ERROR: Running KSycoca failed.
kfmclient(16): No ksycoca4 database available! 

kfmclient(16)/kdecore (trader) KServiceTypeTrader::defaultOffers: KServiceTypeTrader: serviceType  "KUriFilter/Plugin"  not found 
```
OK, so we need to add kbuildsycoca4 to the private-bin list...
Very long output:
[kcoca.txt](https://github.com/netblue30/firejail/files/584185/kcoca.txt)

Ugh, let's try... whitelisting /var/tmp/kdecache-fld/ksycoca4
```
Error: cannot create directory "/var/tmp": Permission denied
trying to create local folder /var/tmp: Permission denied
kbuildsycoca4 running...
Error: cannot create directory "/var/tmp": Permission denied
trying to create local folder /var/tmp: Permission denied
trying to create local folder /var/tmp: Permission denied
trying to create local folder /var/tmp: Permission denied
trying to create local folder /var/tmp: Permission denied
trying to create local folder /var/tmp: Permission denied
kbuildsycoca4: ERROR creating database '/var/tmp/kdecache-fld/ksycoca4'! Insufficient permissions in target directory.
ERROR: Running KSycoca failed.
trying to create local folder /var/tmp: Permission denied
kfmclient(17): No ksycoca4 database available! 
```
FINE, let's whitelist whole /var/tmp

And the output becomes this again:
[kcoca.txt](https://github.com/netblue30/firejail/files/584185/kcoca.txt)

Sigh.

**Comment by netblue30** [comment]
I have removed private-bin from the profile, thanks.
